<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"学生管理",
			            "menuJump":"列表",
			            "tableName":"yonghu"
			        }
			    ],
			    "menu":"学生管理"
			}
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"教师管理",
			            "menuJump":"列表",
			            "tableName":"jiaoshi"
			        }
			    ],
			    "menu":"教师管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"创业案例管理",
                        "menuJump":"列表",
                        "tableName":"chuangyeanli"
                    },
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"案例收藏管理",
					    "menuJump":"列表",
					    "tableName":"chuangyeanliCollection"
					}
                ],
                "menu":"创业案例管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "报名",
                            "删除"
                        ],
                        "menu":"创业项目管理",
                        "menuJump":"列表",
                        "tableName":"chuangyexiangmu"
                    },
					{
					    "buttons":[
					        "查看",
					        "删除"
					    ],
					    "menu":"项目收藏管理",
					    "menuJump":"列表",
					    "tableName":"chuangyexiangmuCollection"
					}
                ],
                "menu":"创业项目管理"
            }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核",
			                "删除"
			            ],
			            "menu":"报名管理",
			            "menuJump":"列表",
			            "tableName":"baoming"
			        }
			    ],
			    "menu":"报名管理"
			}
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"项目分类管理",
                        "menuJump":"列表",
                        "tableName":"dictionary_leix"
                    }
                ],
                "menu":"项目分类管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"获奖项目管理",
                        "menuJump":"列表",
                        "tableName":"huojiang"
                    }
                ],
                "menu":"获奖项目管理"
            }
			
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"创业动态管理",
                        "menuJump":"列表",
                        "tableName":"news"
                    }
                ],
                "menu":"创业动态管理"
            },
			{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "新增",
			                "修改",
			                "删除"
			            ],
			            "menu":"轮播图管理",
			            "menuJump":"列表",
			            "tableName":"config"
			        }
			    ],
			    "menu":"轮播图管理"
			}
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    },
	{
	    "backMenu":[
			{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"创业案例管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangyeanli"
	                }
	            ],
	            "menu":"创业案例管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"创业项目管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangyexiangmu"
	                }
	            ],
	            "menu":"创业项目管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看",
			                "审核"
			            ],
			            "menu":"报名管理",
			            "menuJump":"列表",
			            "tableName":"baoming"
			        }
			    ],
			    "menu":"报名管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"项目分类管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary_leix"
	                }
	            ],
	            "menu":"项目分类管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "新增",
	                        "修改"
	                    ],
	                    "menu":"获奖项目管理",
	                    "menuJump":"列表",
	                    "tableName":"huojiang"
	                }
	            ],
	            "menu":"获奖项目管理"
	        }
			
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"创业动态管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"创业动态管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"教师",
	    "tableName":"jiaoshi"
	},
	{
	    "backMenu":[
			{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"创业案例管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangyeanli"
	                },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"案例收藏管理",
					    "menuJump":"列表",
					    "tableName":"chuangyeanliCollection"
					}
	            ],
	            "menu":"创业案例管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看",
	                        "报名"
	                    ],
	                    "menu":"创业项目管理",
	                    "menuJump":"列表",
	                    "tableName":"chuangyexiangmu"
	                },
					{
					    "buttons":[
					        "查看"
					    ],
					    "menu":"项目收藏管理",
					    "menuJump":"列表",
					    "tableName":"chuangyexiangmuCollection"
					}
	            ],
	            "menu":"创业项目管理"
	        }
			,{
			    "child":[
			        {
			            "buttons":[
			                "查看"
			            ],
			            "menu":"报名管理",
			            "menuJump":"列表",
			            "tableName":"baoming"
			        }
			    ],
			    "menu":"报名管理"
			}
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"项目分类管理",
	                    "menuJump":"列表",
	                    "tableName":"dictionary_leix"
	                }
	            ],
	            "menu":"项目分类管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"获奖项目管理",
	                    "menuJump":"列表",
	                    "tableName":"huojiang"
	                }
	            ],
	            "menu":"获奖项目管理"
	        }
	        ,{
	            "child":[
	                {
	                    "buttons":[
	                        "查看"
	                    ],
	                    "menu":"创业动态管理",
	                    "menuJump":"列表",
	                    "tableName":"news"
	                }
	            ],
	            "menu":"创业动态管理"
	        }
	    ],
	    "frontMenu":[
	
	    ],
	    "roleName":"学生",
	    "tableName":"yonghu"
	}
];

var hasMessage = '';
